databases:
  - name: Motocommerce
    databaseName: motocommercedb
    user: thomasgupta
    plan: free
    region: oregon

services:
  - type: web
    name: whatsapp-ecommerce-bot
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    autoDeploy: true
    healthCheckPath: /
    envVars:
      - key: PORT
        value: 10000
      - key: VERIFY_TOKEN
        sync: false
      - key: WHATSAPP_TOKEN
        sync: false
      - key: WHATSAPP_PHONE_NUMBER_ID
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: Motocommerce
          property: connectionString
      - key: CATALOG_CURRENCY
        value: INR
